### ISSUE TITLE
Readme incorrect

### ISSUE THREAD

**Issue by justinelsberry** [sailthru/sailthru-mobile-android#16]
The readme for version 1.0.1 states the register call should be as follows:

```java
mSailthru.register(RegistrationMode.PROD, "example.sailthru.com", "000000", "123456", Identification.ANONYMOUS, null, "com.example", "0123456789");
```

but  shouldn't the first parameter be of type: ```Sailthru.RegistrationEnvironment.PROD ```

**Comment by lindsayneubauer** [comment]
Yes. README has been updated. Thanks.
